# Generated by Django 5.2 on 2025-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
