# Generated by Django 5.2 on 2025-04-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='verified',
        ),
    ]
