# Generated by Django 5.2 on 2025-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_supabase_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
