# Generated by Django 5.2 on 2025-05-06 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.event'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='reminders_e_user_id_b9702f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['notified'], name='reminders_e_notifie_c0f1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['user', 'timestamp'], name='reminders_r_user_id_09f0ce_idx'),
        ),
    ]
