# Generated by Django 5.2 on 2025-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_event_media_path_event_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='media_path',
        ),
        migrations.AddField(
            model_name='event',
            name='media_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
