# Generated by Django 5.2 on 2025-04-26 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 26, 14, 59, 46, 969052, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
