# Generated by Django 5.2 on 2025-04-28 11:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_event_notified_reminderlog_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remind_days_before',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='reminders_e_user_id_b9702f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['notified'], name='reminders_e_notifie_c0f1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['user', 'timestamp'], name='reminders_r_user_id_09f0ce_idx'),
        ),
    ]
