# Generated by Django 5.2 on 2025-06-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_event_updated_at_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='media_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
