# Generated by Django 5.2 on 2025-06-04 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_event_media_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cultural_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.URLField(max_length=1000)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('gif', 'GIF')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reminders.event')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrationCardPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_pages', to='reminders.event')),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_pages', to='reminders.eventmedia')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_pages', to='reminders.eventmedia')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['image', 'audio', 'gif'])), name='valid_media_type'),
        ),
        migrations.AddConstraint(
            model_name='celebrationcardpage',
            constraint=models.UniqueConstraint(fields=('event', 'page_number'), name='unique_page_per_event'),
        ),
    ]
