# Generated by Django 5.2 on 2025-06-10 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_event_cultural_theme_event_custom_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deletion_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='deletion_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['deletion_notified'], name='reminders_e_deletio_b8e9ad_idx'),
        ),
    ]
