# Generated by Django 5.2 on 2025-06-11 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_event_deletion_notified_event_deletion_scheduled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='eventmedia',
            name='valid_media_type',
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['image', 'audio'])), name='valid_media_type'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
