# Generated by Django 5.2 on 2025-06-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_importlog_remove_eventmedia_valid_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Automatically create event for next year (birthdays/anniversaries only).'),
        ),
    ]
