# Generated by Django 5.2 on 2025-06-14 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0010_event_is_recurring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Mark event as archived (soft delete).'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_archived'], name='reminders_e_is_arch_609de3_idx'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='reminders.event'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reflection',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_reflection_per_event'),
        ),
    ]
