# Generated by Django 5.2 on 2025-06-16 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0011_reflection_event_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reminders.event')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='reminders_c_token_ce419d_idx')],
            },
        ),
    ]
