# Generated by Django 5.2 on 2025-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0013_cardshare_is_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='card_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cardshare',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Mark event as archived.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Automatically create event for next year.'),
        ),
    ]
