# Generated by Django 5.2 on 2025-06-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0014_event_card_password_alter_cardshare_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='media_path',
        ),
        migrations.RemoveField(
            model_name='event',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='media_url',
        ),
    ]
