# Generated by Django 5.2 on 2025-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0015_remove_event_media_path_remove_event_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='media_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='media_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
