# Generated by Django 5.2 on 2025-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0016_event_media_path_event_media_type_event_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
