# Generated by Django 5.2 on 2025-07-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0018_event_auto_share_enabled_event_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('raksha_bandhan', 'Raksha Bandhan'), ('other', 'Other')], max_length=50),
        ),
    ]
