# Generated by Django 5.2 on 2025-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0019_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='card_password',
            field=models.CharField(blank=True, help_text='Hashed password for card access.', max_length=128, null=True),
        ),
    ]
