# Generated by Django 5.2 on 2025-07-26 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0020_alter_event_card_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thread_of_memories_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='reminders.event')),
            ],
            options={
                'ordering': ['year'],
                'constraints': [models.UniqueConstraint(fields=('event', 'year'), name='unique_milestone_per_event_year')],
            },
        ),
    ]
