# Generated by Django 5.2 on 2025-07-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0022_thread_delete_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='thread_of_memories_enabled',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
