# Generated by Django 5.2 on 2025-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0023_remove_event_thread_of_memories_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thread_of_memories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('other', 'Other')], max_length=50),
        ),
    ]
