# Generated by Django 5.2 on 2025-08-02 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0024_event_thread_of_memories_alter_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rakhi_ceremony_notes',
            field=models.TextField(blank=True, help_text='Special notes about the rakhi ceremony', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='raksha_bandhan_theme',
            field=models.CharField(blank=True, choices=[('traditional', 'Traditional'), ('modern', 'Modern'), ('regional', 'Regional'), ('custom', 'Custom')], help_text='Theme for Raksha Bandhan cards', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sacred_promises',
            field=models.TextField(blank=True, help_text='Sacred promises and blessings for Raksha Bandhan', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sibling_relationship',
            field=models.CharField(blank=True, help_text='Brother/Sister/Cousin relationship description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('raksha_bandhan', 'Raksha Bandhan'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='reminders_e_event_t_5e566e_idx'),
        ),
    ]
