# Generated by Django 6.0.2 on 2026-03-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0025_event_rakhi_ceremony_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='birthday_page2_completed',
            field=models.BooleanField(default=False, help_text='Has the user opened the gift/completed the 3-step unwrap ritual?'),
        ),
        migrations.AddField(
            model_name='event',
            name='birthday_page4_wish_made',
            field=models.BooleanField(default=False, help_text='Has the user completed the candle blowing and made a wish?'),
        ),
        migrations.AddField(
            model_name='event',
            name='birthday_page5_seen',
            field=models.BooleanField(default=False, help_text='Has the user reached the finale page?'),
        ),
    ]
