# Generated by Django 6.0.2 on 2026-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0026_event_birthday_page2_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='birthday_page1_seen',
            field=models.BooleanField(default=False, help_text='Has the user entered the birthday intro on page 1?'),
        ),
        migrations.AddField(
            model_name='event',
            name='birthday_unwrap_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current unwrap progression step for page 2 (0-3).'),
        ),
    ]
